/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Collection } from "./Collection";
import { CollectionCountArgs } from "./CollectionCountArgs";
import { CollectionFindManyArgs } from "./CollectionFindManyArgs";
import { Query } from "../../query/base/Query";
import { CollectionFindUniqueArgs } from "./CollectionFindUniqueArgs";
import { CreateCollectionArgs } from "./CreateCollectionArgs";
import { UpdateCollectionArgs } from "./UpdateCollectionArgs";
import { DeleteCollectionArgs } from "./DeleteCollectionArgs";
import { IndexFindManyArgs } from "../../index/base/IndexFindManyArgs";
import { Index } from "../../index/base/Index";
import { DocumentFindManyArgs } from "../../document/base/DocumentFindManyArgs";
import { Document } from "../../document/base/Document";
import { SchemaFindManyArgs } from "../../schema/base/SchemaFindManyArgs";
import { Schema } from "../../schema/base/Schema";
import { SubscriptionFindManyArgs } from "../../subscription/base/SubscriptionFindManyArgs";
import { Subscription } from "../../subscription/base/Subscription";
import { AnalyticsEventFindManyArgs } from "../../analyticsEvent/base/AnalyticsEventFindManyArgs";
import { AnalyticsEvent } from "../../analyticsEvent/base/AnalyticsEvent";
import { CollectionService } from "../collection.service";
@graphql.Resolver(() => Collection)
export class CollectionResolverBase {
  constructor(protected readonly service: CollectionService) {}

  async _collectionsMeta(
    @graphql.Args() args: CollectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Collection])
  async collections(
    @graphql.Args() args: CollectionFindManyArgs
  ): Promise<Collection[]> {
    return this.service.collections(args);
  }

  @graphql.Query(() => Collection, { nullable: true })
  async collection(
    @graphql.Args() args: CollectionFindUniqueArgs
  ): Promise<Collection | null> {
    const result = await this.service.collection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Collection)
  async createCollection(
    @graphql.Args() args: CreateCollectionArgs
  ): Promise<Collection> {
    return await this.service.createCollection({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Collection)
  async updateCollection(
    @graphql.Args() args: UpdateCollectionArgs
  ): Promise<Collection | null> {
    try {
      return await this.service.updateCollection({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Collection)
  async deleteCollection(
    @graphql.Args() args: DeleteCollectionArgs
  ): Promise<Collection | null> {
    try {
      return await this.service.deleteCollection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Index], { name: "indices" })
  async findIndices(
    @graphql.Parent() parent: Collection,
    @graphql.Args() args: IndexFindManyArgs
  ): Promise<Index[]> {
    const results = await this.service.findIndices(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Document], { name: "documents" })
  async findDocuments(
    @graphql.Parent() parent: Collection,
    @graphql.Args() args: DocumentFindManyArgs
  ): Promise<Document[]> {
    const results = await this.service.findDocuments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Schema], { name: "schemata" })
  async findSchemata(
    @graphql.Parent() parent: Collection,
    @graphql.Args() args: SchemaFindManyArgs
  ): Promise<Schema[]> {
    const results = await this.service.findSchemata(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Subscription], { name: "subscriptions" })
  async findSubscriptions(
    @graphql.Parent() parent: Collection,
    @graphql.Args() args: SubscriptionFindManyArgs
  ): Promise<Subscription[]> {
    const results = await this.service.findSubscriptions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [AnalyticsEvent], { name: "analyticsEvents" })
  async findAnalyticsEvents(
    @graphql.Parent() parent: Collection,
    @graphql.Args() args: AnalyticsEventFindManyArgs
  ): Promise<AnalyticsEvent[]> {
    const results = await this.service.findAnalyticsEvents(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
