/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BackupService } from "../backup.service";
import { BackupCreateInput } from "./BackupCreateInput";
import { Backup } from "./Backup";
import { BackupFindManyArgs } from "./BackupFindManyArgs";
import { BackupWhereUniqueInput } from "./BackupWhereUniqueInput";
import { BackupUpdateInput } from "./BackupUpdateInput";
import { RestorePointFindManyArgs } from "../../restorePoint/base/RestorePointFindManyArgs";
import { RestorePoint } from "../../restorePoint/base/RestorePoint";
import { RestorePointWhereUniqueInput } from "../../restorePoint/base/RestorePointWhereUniqueInput";

export class BackupControllerBase {
  constructor(protected readonly service: BackupService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Backup })
  async createBackup(@common.Body() data: BackupCreateInput): Promise<Backup> {
    return await this.service.createBackup({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Backup] })
  @ApiNestedQuery(BackupFindManyArgs)
  async backups(@common.Req() request: Request): Promise<Backup[]> {
    const args = plainToClass(BackupFindManyArgs, request.query);
    return this.service.backups({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Backup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async backup(
    @common.Param() params: BackupWhereUniqueInput
  ): Promise<Backup | null> {
    const result = await this.service.backup({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Backup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateBackup(
    @common.Param() params: BackupWhereUniqueInput,
    @common.Body() data: BackupUpdateInput
  ): Promise<Backup | null> {
    try {
      return await this.service.updateBackup({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Backup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBackup(
    @common.Param() params: BackupWhereUniqueInput
  ): Promise<Backup | null> {
    try {
      return await this.service.deleteBackup({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/restorePoints")
  @ApiNestedQuery(RestorePointFindManyArgs)
  async findRestorePoints(
    @common.Req() request: Request,
    @common.Param() params: BackupWhereUniqueInput
  ): Promise<RestorePoint[]> {
    const query = plainToClass(RestorePointFindManyArgs, request.query);
    const results = await this.service.findRestorePoints(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        startTime: true,

        backup: {
          select: {
            id: true,
          },
        },

        status: true,
        endTime: true,
        restoredBy: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/restorePoints")
  async connectRestorePoints(
    @common.Param() params: BackupWhereUniqueInput,
    @common.Body() body: RestorePointWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      restorePoints: {
        connect: body,
      },
    };
    await this.service.updateBackup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/restorePoints")
  async updateRestorePoints(
    @common.Param() params: BackupWhereUniqueInput,
    @common.Body() body: RestorePointWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      restorePoints: {
        set: body,
      },
    };
    await this.service.updateBackup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/restorePoints")
  async disconnectRestorePoints(
    @common.Param() params: BackupWhereUniqueInput,
    @common.Body() body: RestorePointWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      restorePoints: {
        disconnect: body,
      },
    };
    await this.service.updateBackup({
      where: params,
      data,
      select: { id: true },
    });
  }
}
