/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { QueryService } from "../query.service";
import { QueryCreateInput } from "./QueryCreateInput";
import { Query } from "./Query";
import { QueryFindManyArgs } from "./QueryFindManyArgs";
import { QueryWhereUniqueInput } from "./QueryWhereUniqueInput";
import { QueryUpdateInput } from "./QueryUpdateInput";
import { SubscriptionFindManyArgs } from "../../subscription/base/SubscriptionFindManyArgs";
import { Subscription } from "../../subscription/base/Subscription";
import { SubscriptionWhereUniqueInput } from "../../subscription/base/SubscriptionWhereUniqueInput";
import { QueryCacheFindManyArgs } from "../../queryCache/base/QueryCacheFindManyArgs";
import { QueryCache } from "../../queryCache/base/QueryCache";
import { QueryCacheWhereUniqueInput } from "../../queryCache/base/QueryCacheWhereUniqueInput";

export class QueryControllerBase {
  constructor(protected readonly service: QueryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Query })
  async createQuery(@common.Body() data: QueryCreateInput): Promise<Query> {
    return await this.service.createQuery({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Query] })
  @ApiNestedQuery(QueryFindManyArgs)
  async queries(@common.Req() request: Request): Promise<Query[]> {
    const args = plainToClass(QueryFindManyArgs, request.query);
    return this.service.queries({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Query })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async query(
    @common.Param() params: QueryWhereUniqueInput
  ): Promise<Query | null> {
    const result = await this.service.query({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Query })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateQuery(
    @common.Param() params: QueryWhereUniqueInput,
    @common.Body() data: QueryUpdateInput
  ): Promise<Query | null> {
    try {
      return await this.service.updateQuery({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Query })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteQuery(
    @common.Param() params: QueryWhereUniqueInput
  ): Promise<Query | null> {
    try {
      return await this.service.deleteQuery({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/subscriptions")
  @ApiNestedQuery(SubscriptionFindManyArgs)
  async findSubscriptions(
    @common.Req() request: Request,
    @common.Param() params: QueryWhereUniqueInput
  ): Promise<Subscription[]> {
    const query = plainToClass(SubscriptionFindManyArgs, request.query);
    const results = await this.service.findSubscriptions(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        event: true,

        user: {
          select: {
            id: true,
          },
        },

        collection: {
          select: {
            id: true,
          },
        },

        query: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/subscriptions")
  async connectSubscriptions(
    @common.Param() params: QueryWhereUniqueInput,
    @common.Body() body: SubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subscriptions: {
        connect: body,
      },
    };
    await this.service.updateQuery({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/subscriptions")
  async updateSubscriptions(
    @common.Param() params: QueryWhereUniqueInput,
    @common.Body() body: SubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subscriptions: {
        set: body,
      },
    };
    await this.service.updateQuery({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/subscriptions")
  async disconnectSubscriptions(
    @common.Param() params: QueryWhereUniqueInput,
    @common.Body() body: SubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subscriptions: {
        disconnect: body,
      },
    };
    await this.service.updateQuery({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/queryCaches")
  @ApiNestedQuery(QueryCacheFindManyArgs)
  async findQueryCaches(
    @common.Req() request: Request,
    @common.Param() params: QueryWhereUniqueInput
  ): Promise<QueryCache[]> {
    const query = plainToClass(QueryCacheFindManyArgs, request.query);
    const results = await this.service.findQueryCaches(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        result: true,
        expiresAt: true,

        query: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/queryCaches")
  async connectQueryCaches(
    @common.Param() params: QueryWhereUniqueInput,
    @common.Body() body: QueryCacheWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      queryCaches: {
        connect: body,
      },
    };
    await this.service.updateQuery({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/queryCaches")
  async updateQueryCaches(
    @common.Param() params: QueryWhereUniqueInput,
    @common.Body() body: QueryCacheWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      queryCaches: {
        set: body,
      },
    };
    await this.service.updateQuery({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/queryCaches")
  async disconnectQueryCaches(
    @common.Param() params: QueryWhereUniqueInput,
    @common.Body() body: QueryCacheWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      queryCaches: {
        disconnect: body,
      },
    };
    await this.service.updateQuery({
      where: params,
      data,
      select: { id: true },
    });
  }
}
