import { JsonValue } from "type-fest";

export type Plugin = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  version: number | null;
  description: string | null;
  entryPoint: string | null;
  configField: JsonValue;
  isActive: boolean | null;
  installedAt: Date | null;
  name: string | null;
  pluginVersion: number | null;
  configuration: JsonValue;
  updatedOn: Date | null;
  pluginEntryPoint: string | null;
  pluginConfiguration: JsonValue;
  pluginIsActive: boolean | null;
  pluginName: string | null;
  pluginDescription: string | null;
  pluginInstalledAt: Date | null;
  pluginUpdatedAt: Date | null;
  pluginDesc: string | null;
  pluginInstalled: Date | null;
  pluginVer: number | null;
  pluginEntry: string | null;
  pluginConf: JsonValue;
  pluginActive: boolean | null;
  pluginUpdated: Date | null;
  pluginVerField: number | null;
  pluginDescField: string | null;
  pluginEntryField: string | null;
  pluginConfField: JsonValue;
  pluginInstalledField: Date | null;
  pluginActiveField: boolean | null;
  pluginUpdatedField: Date | null;
  pluginNameField: string | null;
};
