import { StringFilter } from "../../util/StringFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";

export type PluginWhereInput = {
  id?: StringFilter;
  version?: IntNullableFilter;
  description?: StringNullableFilter;
  entryPoint?: StringNullableFilter;
  configField?: JsonFilter;
  isActive?: BooleanNullableFilter;
  installedAt?: DateTimeNullableFilter;
  name?: StringNullableFilter;
  pluginVersion?: IntNullableFilter;
  configuration?: JsonFilter;
  updatedOn?: DateTimeNullableFilter;
  pluginEntryPoint?: StringNullableFilter;
  pluginConfiguration?: JsonFilter;
  pluginIsActive?: BooleanNullableFilter;
  pluginName?: StringNullableFilter;
  pluginDescription?: StringNullableFilter;
  pluginInstalledAt?: DateTimeNullableFilter;
  pluginUpdatedAt?: DateTimeNullableFilter;
  pluginDesc?: StringNullableFilter;
  pluginInstalled?: DateTimeNullableFilter;
  pluginVer?: IntNullableFilter;
  pluginEntry?: StringNullableFilter;
  pluginConf?: JsonFilter;
  pluginActive?: BooleanNullableFilter;
  pluginUpdated?: DateTimeNullableFilter;
  pluginVerField?: IntNullableFilter;
  pluginDescField?: StringNullableFilter;
  pluginEntryField?: StringNullableFilter;
  pluginConfField?: JsonFilter;
  pluginInstalledField?: DateTimeNullableFilter;
  pluginActiveField?: BooleanNullableFilter;
  pluginUpdatedField?: DateTimeNullableFilter;
  pluginNameField?: StringNullableFilter;
};
