import { SortOrder } from "../../util/SortOrder";

export type PluginOrderByInput = {
  id?: SortOrder;
  createdAt?: SortOrder;
  updatedAt?: SortOrder;
  version?: SortOrder;
  description?: SortOrder;
  entryPoint?: SortOrder;
  configField?: SortOrder;
  isActive?: SortOrder;
  installedAt?: SortOrder;
  name?: SortOrder;
  pluginVersion?: SortOrder;
  configuration?: SortOrder;
  updatedOn?: SortOrder;
  pluginEntryPoint?: SortOrder;
  pluginConfiguration?: SortOrder;
  pluginIsActive?: SortOrder;
  pluginName?: SortOrder;
  pluginDescription?: SortOrder;
  pluginInstalledAt?: SortOrder;
  pluginUpdatedAt?: SortOrder;
  pluginDesc?: SortOrder;
  pluginInstalled?: SortOrder;
  pluginVer?: SortOrder;
  pluginEntry?: SortOrder;
  pluginConf?: SortOrder;
  pluginActive?: SortOrder;
  pluginUpdated?: SortOrder;
  pluginVerField?: SortOrder;
  pluginDescField?: SortOrder;
  pluginEntryField?: SortOrder;
  pluginConfField?: SortOrder;
  pluginInstalledField?: SortOrder;
  pluginActiveField?: SortOrder;
  pluginUpdatedField?: SortOrder;
  pluginNameField?: SortOrder;
};
